import "@mantine/carousel/styles.css";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import {
  ColorSchemeScript,
  createTheme,
  MantineColorsTuple,
  MantineProvider,
} from "@mantine/core";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "FrostyDeligths",
  description: "Generated by create next app",
};

const themeOveride: MantineColorsTuple = [
  "#f2f8f4",
  "#e5ede7",
  "#c5d9cb",
  "#a4c5ad",
  "#87b593",
  "#74aa82",
  "#6ba57a",
  "#599067",
  "#4d805b",
  "#3e6f4c",
];

const theme = createTheme({
  colors: {
    themeOveride,
  },
});

// const resolver: CSSVariablesResolver = (theme) => ({
//   variables: {
//     "--mantine-background-light": theme.colors.myColor[5],
//   },
//   light: {},
//   dark: {},
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <head>
          <ColorSchemeScript />
        </head>
        <body>
          <MantineProvider
            // defaultColorScheme="dark"
            theme={{ ...theme, primaryColor: "green" }}
          >
            {children}
          </MantineProvider>
        </body>
      </body>
    </html>
  );
}
