import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import "@mantine/carousel/styles.css";
import "@mantine/core/styles.css";

import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  MantineColorsTuple,
} from "@mantine/core";
import { Navbar } from "@/components/ui/Navbar";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "EisFabrik",
  description: "Generated by create next app",
};

const myColor: MantineColorsTuple = [
  "#e3ffed",
  "#ccffdd",
  "#9bffbc",
  "#64ff98",
  "#3aff79",
  "#1fff66",
  "#09ff5b",
  "#00e34a",
  "#00ca40",
  "#00ae31",
];

const theme = createTheme({
  colors: {
    myColor,
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <head>
          <ColorSchemeScript />
        </head>
        <body>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </body>
      </body>
    </html>
  );
}
