import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import "@mantine/carousel/styles.css";
import "@mantine/core/styles.css";

import {
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  MantineColorsTuple,
  CSSVariablesResolver,
} from "@mantine/core";
import { Navbar } from "@/components/ui/Navbar";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "EisFabrik",
  description: "Generated by create next app",
};

const themeOveride: MantineColorsTuple = [
  "#ebfff9",
  "#d6fdf2",
  "#a8fde3",
  "#77fdd4",
  "#57fdc7",
  "#47fdbf",
  "#3ffdba",
  "#33e2a4",
  "#25c891",
  "#00ad7b",
];

const theme = createTheme({
  colors: {
    themeOveride,
  },
});

// const resolver: CSSVariablesResolver = (theme) => ({
//   variables: {
//     "--mantine-background-light": theme.colors.myColor[5],
//   },
//   light: {},
//   dark: {},
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <head>
          <ColorSchemeScript />
        </head>
        <body>
          <MantineProvider
            // defaultColorScheme="dark"
            theme={{ ...theme, primaryColor: "green" }}
          >
            {children}
          </MantineProvider>
        </body>
      </body>
    </html>
  );
}
